version: "3"
services:
  teamlock:
    image: raznak/teamlock
    ports:
      - 8000:8000
    environment:
      APP_URL: https://demo.teamlock.io # URL to reach Teamlock. This will be used to send registration email
      DEBUG: "false"
      MONGO_HOST: mongodb://mongo:27017
      MONGO_DATABASE: teamlock
      # MONGO_USER: teamlock
      # MONGO_PASSWORD: teamlock
      # MONGO_AUTHSOURCE: teamlock
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SMTP_AUTH: "false"
      SMTP_HOST: 172.16.1.3
      SMTP_PORT: 25
      SMTP_SSL: "false"
      SMTP_EMAIL: contact@teamlock.io
      SECRET_KEY: AREALYSTRONGSECRETKEY
    volumes:
      - /var/log/teamlock:/var/log/teamlock
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongodata:/data/db

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  mongodata:
    driver: local
  redis_data:
    driver: local
