name: Docker Image CI

on:
  push:
    branches: [main]

env:
  VERSION: "1.0"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: sudo docker build -t teamlock:$VERSION --build-arg VERSION=$VERSION .

  deploy:
    runs-on: self-hosted
    needs: build
    env:
      PERSONNAL_TOKEN: ${{ secrets.PERSONNAL_TOKEN }}
    steps:
      - name: Login on Container registry
        run: echo $PERSONNAL_TOKEN | sudo docker login ghcr.io -u raznak --password-stdin
      - name: Tag the image
        run: sudo docker tag teamlock:$VERSION ghcr.io/teamlock/teamlock:$VERSION
      - name: Push the image
        run: sudo docker push ghcr.io/teamlock/teamlock:$VERSION
